title: Dev's homepage
description: Sharing deep .NET insights and real-world solutions.
url: "https://givikdev.github.io"
lang: en
author: Givi Kesanashvili

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    github: givikdev
    linkedin: givikesanashvili

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
