title: Journey to Modernization with .NET
description: >
  Exploring the backend slice of the modernization journey with a focus on the .NET ecosystem. 
  Discover each component—what it solves, when to apply it, and how to adapt it to evolving project requirements.
author:
  name: GiviKDev

lang: en

remote_theme: jekyll/minima

minima:
  skin: auto
  nav_pages:
    - posts.md
    - about.md
  show_excerpts: true
  social_links:
    - title: GiviKDev at GitHub
      icon: github
      url: https://github.com/GiviKDev
    - title: Givi Kesanashvili at LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/givikesanashvili/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
