title: Dev's homepage
description: >
  Real‑world .NET 8/9 development insights—deep dives into ASP.NET Core features,
  architecture patterns, clean code, testability, and reusable code samples.
author:
  name: GiviKDev

lang: en

remote_theme: jekyll/minima

minima:
  skin: auto
  nav_pages:
    - about.md
  show_excerpts: true
  social_links:
    - title: GiviKDev at GitHub
      icon: github
      url: "https://github.com/GiviKDev"
    - title: Givi Kesanashvili at LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/givikesanashvili/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
